copy i:\modules\*.c a:\modules\*.c
copy i:\modules\*.h a:\modules\*.h
copy i:\modules\*.scl a:\modules\*.scl
copy i:\modules\*.tun a:\modules\*.tun
copy i:\modules\*.man a:\modules\*.man
copy i:\modules\*.drv a:\modules\*.drv
copy i:\scales.rsc a:\modules\scales.rsc
copy i:\scales.hrd a:\modules\scales.hrd
copy i:\scales.h a:\modules\scales.h
mkdir a:\modules\docs
copy i:\modules\docs\*.* a:\modules\docs\*.*



