
#define	MENU1	    0

#define MTDesk	    3
#define MTFile	    4
#define MTScales	    5
#define MTKey	    6
#define MTNotes	    7
#define MAbout	   10
#define MQuit	   19
#define MLoadScales	   20
#define MSaveScales	   21
#define MSaveDefaults	   23
#define MLoadDefaults	   25
#define MLoadTunings	   26
#define MPrintText	   27
#define MPaths	   30
#define MStoreScale	   32
#define MLoadScale	   33
#define MDisplayOptions	   35
#define MDeleteScale	   36
#define MStoreAs	   37
#define MRename	   38
#define MSortNames	   39
#define MEbkey	   43
#define MAkey	   44
#define MAbkey	   45
#define MGbkey	   46
#define MDkey	   47
#define MDbkey	   48
#define MBkey	   49
#define MCkey	   50
#define MGkey	   51
#define MFkey	   52
#define MEkey	   53
#define MBbkey	   54
#define MGscale	   56
#define MFscale	   57
#define MEbscale	   58
#define MDbscale	   59
#define MCscale	   60
#define MAbscale	   61
#define MBscale	   62
#define MBbscale	   63
#define MAscale	   64
#define MEscale	   65
#define MDscale	   66
#define MGbscale	   67

#define	FAboutMono	    1


#define	FAbout	    2

#define about_version	    5
#define about_circa	    7
#define about_time	    8
#define about_date	    9
#define about_scalesmem	   12
#define about_tuningsmem	   14

#define	FAboutLow	    3


#define	NAME_SCALE	    4

#define FScaleEntryTitle	    1
#define FEditName	    2
#define FEditScaleOK	    3
#define FEditScaleCancel	    4

#define	NAME_SCALE_SMALL	    5

#define FSmallScaleTitle	    1
#define FSmallScaleName	    2
#define FSmallScaleOK	    3
#define FSmallScaleCancl	    4

#define	FNoteOnFretboard	    6

#define FNoteOnBack	    0
#define ParentRadioNotes	    5
#define FNoteInScaleTick	    7
#define FNoteInScaleCros	    8
#define FNoteOnFretName	    9
#define FNoteOnFretNum	   10
#define FNoteOnStringNum	   11
#define FNoteOnFretOK	   12
#define FNoteOnFretCancl	   13

#define	Clash_resolve	    7

#define FScaleStorageTtl	    1
#define ClashNameField	    2
#define ClashNoteField	    3
#define ClashNameTitlea	    4
#define ClashNoteTitlea	    5
#define ClashCancel	    6
#define ClashRename	    7
#define ClashStoreIt	    8

#define	Clash_Resolve_Sm	    8

#define SmallClashName	    1
#define SmallClashNotes	    2
#define ClashNameTitleb	    3
#define ClashNoteTitleb	    4
#define ClashFormTitleb	    5
#define SmallClashCancel	    6
#define SmallClashRename	    7
#define SmallClashStoreT	    8

#define	FPrintAsText	    9

#define FTPrintTitle	    1
#define FTPheadtitle	    2
#define FHeader1	    3
#define FHeader2	    4
#define FTPtrailtitl	    5
#define FTrailer1	    6
#define FTrailer2	    7
#define FTPTabTitle	    8
#define FTabs	    9
#define FTPFretsTitle	   10
#define FFrets	   11
#define FTPStartTitle	   12
#define FStartFret	   13
#define FTextPrintPrint	   14
#define FTextPrintToDisk	   15
#define FTextPrintCancel	   16
#define PrintDriverName	   17

#define	FDisplayOptions	   10

#define FDisplaOptTitle	    1
#define FFretsWidthTitle	    3
#define FFretsHeightTitl	    4
#define FFret_width	    5
#define FFret_height	    6
#define FFretsDisplaTitl	   10
#define FFretsDisplaEdit	   11
#define FIncTitle	   14
#define FFirstFretEdit	   15
#define FStartFretTitle	   16
#define FIncrementEdit	   17
#define FMiscButtons	   18
#define FRootButton	   20
#define FRelativeButton	   21
#define FNumbersButton	   22
#define FScaleNameButton	   23
#define FKeyNameButton	   24
#define FOptionsOK	   25
#define FOptionsCancel	   26
#define FNotesDisplayAs	   27
#define FCircularButton	   28
#define FSquareNotes	   29
#define FTextNotes	   30

#define	FOctave_form	   11

#define FOctaveBackdrop	    0
#define FOctaveOK	    2
#define FOctaveCANCEL	    3
#define FOctavem3	    4
#define FOctavem2	    5
#define FOctavem1	    6
#define FOctave0	    7
#define FOctave1	    8
#define FOctave2	    9
#define FOctave3	   10

#define	FTuning_form	   12

#define FTuningBackdrop	    0
#define FString1Name	    8
#define FString2Name	    9
#define FString3Name	   10
#define FString4Name	   11
#define FString5Name	   12
#define FString6Name	   13
#define FTuningMidiRadio	   14
#define FTuningChipRadio	   15
#define FString1Octave	   16
#define FString1Play	   17
#define FString1Right	   18
#define FString1Left	   19
#define FString2Left	   20
#define FString3Left	   21
#define FString4Left	   22
#define FString5Left	   23
#define FString6Left	   24
#define FString2Right	   25
#define FString3Right	   26
#define FString4Right	   27
#define FString5Right	   28
#define FString6Right	   29
#define FString2Octave	   30
#define FString3Octave	   31
#define FSrtring4Octave	   32
#define FString5Octave	   33
#define FString6Octave	   34
#define FString2Play	   35
#define FString3Play	   36
#define FString4Play	   37
#define FString5Play	   38
#define FString6Play	   39
#define FTuningOK	   40
#define FTuningCANCEL	   41
#define FTuningLOAD	   42
#define FTuningSAVE	   43
#define FTuningRESTORE	   44
#define FTuningSTORE	   45
#define FTuningName	   46
#define FOctaveName	   47
#define TunerPlayButton	   48
#define TunnerNoteButton	   49
#define MidiSetupButton	   51
#define FChipSetup	   52
#define DialogueSwitch1	   53
#define BTuningDelete	   54

#define	FMidiSetup	   13

#define MidiChannelNum	    4
#define MidiVelocityNum	    5
#define MidiSetupRadios	    6
#define MidiNoteOffRadio	    7
#define MidiVel0Radio	    8
#define MidiSetupOK	    9
#define MidiSetupCANCEL	   10

#define	FChipVolume	   14

#define Fchipvol	    3
#define chip_volumeOK	    4
#define chip_volumeCNCL	    5

#define	FDefault_paths	   15

#define ScalesPathLow	    1
#define TuningPathLow	    2
#define PathsOK	    6
#define PathsSAVE	    7
#define PathsCANCEL	    8
#define DefaultsPathLow	    9
#define PrinterPathLow	   12

#define	WaitForm	   16

#define WaitMessage	    2

#define	FNoteLength	   17

#define NoteLength	    3
#define NoteLengthOK	    4
#define NoteLengthCANCEL	    5

#define	FORM16	   18

#define DialogueSwitch2	    2
#define TuningDelete	   30

#define	Help_Key	   19

#define NormalNoteBox	    2
#define RootNoteBox	    3
#define RelativeNoteBox	    4
#define NormRelBox	    9
#define RootRelBox	   10
#define HelpKeyOK	   14

#define	TextWinHelp	   20


#define	NAG_SCREEN	   21

#define Please_Wait_Butt	    1

#define	FORM23	   22


#define	FORM24	   23

